name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ README.md ]
  workflow_dispatch:
  
jobs:
  formatlint:
    name: Format linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: GitHub Action for SwiftFormat
        uses: CassiusPacheco/action-swiftformat@v0.1.0
        with:
          swiftformat-version: '0.49.11'

  # Disabled until https://github.com/paulofaria/test-reporter is updated to Swift 5.4
  macos:
    name: Build and test on macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set code coverage path 
      run: echo "codecov_path=$(swift test --show-codecov-path)" >> $GITHUB_ENV
    - name: Test and publish code coverage to Code Climate
      uses: paulofaria/codeclimate-action@master
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        downloadUrl: https://github.com/paulofaria/test-reporter/releases/download/0.9.0/test-reporter-0.9.0-darwin-amd64
        coverageCommand: swift test --enable-test-discovery --enable-code-coverage
        coverageLocations: ${{ env.codecov_path }}:lcov-json

  # ubuntu-latest is ubuntu-22.04 currently. Swift versions older than 5.7 don't have builds for 22.04. https://www.swift.org/download/ 
  ubuntu-old:
    name: Build ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] 
        swift: ["5.4", "5.5", "5.6"]
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Test
      run: swift test

  ubuntu-latest:
    name: Build ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] 
        swift: ["5.7"]
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Test
      run: swift test
